#!/usr/bin/env bash
#
# bootstrap installs things.

cd "$(dirname "$0")/.."
DOTFILES_ROOT=$(pwd -P)

set -e

echo ''

info () {
  printf "\r  [ \033[00;34m..\033[0m ] $1\n"
}

user () {
  printf "\r  [ \033[0;33m??\033[0m ] $1\n"
}

success () {
  printf "\r\033[2K  [ \033[00;32mOK\033[0m ] $1\n"
}

fail () {
  printf "\r\033[2K  [\033[0;31mFAIL\033[0m] $1\n"
  echo ''
  exit
}

setup_renater_certificate () {
  renater_certificate=false
  user "Install renater certificate for irstea forge \n\
        [y]es, [n]o"
  read -n 1 action
  case "$action" in
    y )
      renater_certificate=true;;
    * )
      info "Renater certificate not installed";;
  esac

  if [ "$renater_certificate" == "true" ]
  then
    sudo wget -O /usr/local/share/ca-certificates/TCS-CA-CHAIN-SHA1.crt 'https://services.renater.fr/_media/tcs/tcschain.crt?cache=nocache'
    sudo wget -O /usr/local/share/ca-certificates/TCS-CA-CHAIN-SHA2.crt 'https://services.renater.fr/_media/tcs/serveur/cachain.txt?cache=nocache'
    if [ -f /usr/local/share/ca-certificates/TCS-CA-CHAIN-SHA1.crt ] && [ -f /usr/local/share/ca-certificates/TCS-CA-CHAIN-SHA2.crt ]
    then
      sudo update-ca-certificates
      success "Update ca certificates should be good"
    else
      fail "Cannot access to https://services.renater.fr"
    fi
  fi
}

setup_gitconfig () {
  if ! [ -f git/gitconfig.symlink ]
  then
    info 'setup gitconfig'

    user ' - What is your git author name?'
    read -e git_authorname
    user ' - What is your git author email?'
    read -e git_authoremail

    sed -e "s/AUTHORNAME/$git_authorname/g" -e "s/AUTHOREMAIL/$git_authoremail/g" git/gitconfig.symlink.example > git/gitconfig.symlink

    success 'gitconfig'
  fi
}


link_file () {
  local src=$1 dst=$2

  local overwrite= backup= skip=
  local action=

  if [ -f "$dst" -o -d "$dst" -o -L "$dst" ]
  then

    if [ "$overwrite_all" == "false" ] && [ "$backup_all" == "false" ] && [ "$skip_all" == "false" ]
    then

      local currentSrc="$(readlink $dst)"

      if [ "$currentSrc" == "$src" ]
      then

        skip=true;

      else

        user "File already exists: $dst ($(basename "$src")), what do you want to do?\n\
        [s]kip, [S]kip all, [o]verwrite, [O]verwrite all, [b]ackup, [B]ackup all?"
        read -n 1 action

        case "$action" in
          o )
            overwrite=true;;
          O )
            overwrite_all=true;;
          b )
            backup=true;;
          B )
            backup_all=true;;
          s )
            skip=true;;
          S )
            skip_all=true;;
          * )
            ;;
        esac

      fi

    fi

    overwrite=${overwrite:-$overwrite_all}
    backup=${backup:-$backup_all}
    skip=${skip:-$skip_all}

    if [ "$overwrite" == "true" ]
    then
      rm -rf "$dst"
      success "removed $dst"
    fi

    if [ "$backup" == "true" ]
    then
      mv "$dst" "${dst}.backup"
      success "moved $dst to ${dst}.backup"
    fi

    if [ "$skip" == "true" ]
    then
      success "skipped $src"
    fi
  fi

  if [ "$skip" != "true" ]  # "false" or empty
  then
    ln -s "$1" "$2"
    success "linked $1 to $2"
  fi
}

install_dotfiles () {
  info 'installing dotfiles'

  local overwrite_all=false backup_all=false skip_all=false

  for src in $(find -H "$DOTFILES_ROOT" -maxdepth 2 -name '*.symlink' -not -path '*.git*')
  do
    dst="$HOME/.$(basename "${src%.*}")"
    link_file "$src" "$dst"
  done
}

install_qtcreatorfiles () {

  local overwrite_all=false backup_all=false skip_all=false
  local qtproject="$HOME/.config/QtProject/"
  local dst="${qtproject}/qtcreator/generic-highlighter/"
  mkdir -p $dst 
  link_file "$DOTFILES_ROOT/qtcreator/xml.xml" "${dst}xml.xml"
  success 'installed qtcreator xml.xml'

  local dst2="${qtproject}/qtcreator/codestyles/Cpp/"
  mkdir -p $dst2 
  link_file "$DOTFILES_ROOT/qtcreator/codingstyle.xml" "${dst2}codingstyle.xml"
  sed -i 's/CurrentPreferences=.*/CurrentPreferences=@ByteArray(codingstyle)/' "${qtproject}QtCreator.ini"
  success 'installed qtcreator codingstyle.xml'


}

setup_gitconfig
install_dotfiles
install_qtcreatorfiles
setup_renater_certificate


echo ''
echo '  All installed!'
